#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# Created by i@BlahGeek.com at 2014-12-13

import sys
import os

if len(sys.argv) < 3:
    print('Usage:', sys.argv[0], '<IMG> <OUTPUT>')
    sys.exit(-1)

sys.stderr.write("Converting {} to {}...".format(sys.argv[1], sys.argv[2]))

img = open(sys.argv[1]).read()
if not os.path.exists(os.path.dirname(sys.argv[2])):
    os.makedirs(os.path.dirname(sys.argv[2]))
fout = open(sys.argv[2], 'w')

fout.write('// Automaticlly generated by logo_converter.py by blahgeek\n')
fout.write('// From ' + sys.argv[1] + '\n')

fout.write('const unsigned char OCTVR_LOGO_DATA[] = {\n')
for i, c in enumerate(img):
    fout.write('{}, '.format(ord(c)))
    if i % 20 == 0:
        fout.write('\n')
fout.write('0 }; \n')

fout.close()
