#!/usr/bin/env python2
# -*- coding: utf-8 -*-
# Created by i@BlahGeek.com at 2014-12-13

import sys
import os
import io

if len(sys.argv) < 3:
    print('Usage:', sys.argv[0], '<IMG> <OUTPUT>')
    sys.exit(-1)

sys.stderr.write("Converting {} to {}...\n".format(sys.argv[1], sys.argv[2]))

img = io.open(sys.argv[1], 'rb').read()
if not os.path.exists(os.path.dirname(sys.argv[2])):
    os.makedirs(os.path.dirname(sys.argv[2]))
fout = open(sys.argv[2], 'w')

fout.write('// Automaticlly generated by logo_converter.py by blahgeek\n')
fout.write('// From ' + sys.argv[1] + '\n')

fout.write('extern const unsigned char OCTVR_LOGO_DATA[];\n')
fout.write('extern const int OCTVR_LOGO_DATA_LEN;\n')
fout.write('const unsigned char OCTVR_LOGO_DATA[] = {\n')

if sys.version[0] == '3':
    byte_to_ascii = lambda x : x
else:
    byte_to_ascii = lambda x : ord(x)

for i, c in enumerate(img):
    fout.write('{}, '.format(byte_to_ascii(c)))
    if i % 20 == 0:
        fout.write('\n')
fout.write('}; \n')
fout.write('const int OCTVR_LOGO_DATA_LEN = {};'.format(len(img)))

fout.close()
